""" 
1) raead & Load documents (Pdf in our experiment)
2) pass documents to splitter (RecursiveCharacterTextSplitter)
3) call model for embedding the splitted documents or chunks
4) Initialize pinecone index and may use namespaces for organize data
5) embedded vector saved into vectoreDB for recall that later
6) use llm (llama-3.1-8b-instant, from Groq) and pass system prompt to it
7) Integrate retriever with llm chain to make RAG pipeline
8) Create flask API that handles user input and returns responses generated by our RAG .

"""